version: "3.3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
      - /app/node_modules

  api:
    container_name: api
    build: ./api
    command: bash -c "rake db:create && rake db:migrate"
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    env_file: ./database.env
